jobs:
- job: linux
  container: nv-bionic-wasm

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget

  steps:
  - checkout: self
    clean: true
  
  - bash: |
      cd /emsdk
      sudo git reset HEAD --hard
      sudo git pull
      sudo ./emsdk update-tags
      sudo ./emsdk install 1.38.45-upstream
      sudo ./emsdk activate 1.38.45-upstream
      sudo chmod -R 777 /emsdk
      sudo chmod -R 777 ~/.emscripten_cache

    displayName: 'Setup Emscripten'

  - bash: |
      cd /emsdk
      wget https://raw.githubusercontent.com/mono/mono/master/sdks/builds/emscripten-pr-8457.diff
      wget https://raw.githubusercontent.com/mono/mono/master/sdks/builds/fix-emscripten-8511.diff
      cd /emsdk/upstream/emscripten
      patch -N -p1 < /emsdk/emscripten-pr-8457.diff
      patch -N -p1 < /emsdk/fix-emscripten-8511.diff

    displayName: 'Apply Emscripten Mono patches'

  - task: GitVersion@4
    inputs:
      updateAssemblyInfo: false

  - script: |
      source /emsdk/emsdk_env.sh
      cd src/CalcManager
      chmod +x build.sh
      ./build.sh

    displayName: 'Build Wasm CalcManager'

    env:
      GITVERSION_FullSemVer: $(GITVERSION_FullSemVer)

  - script: |
      source /emsdk/emsdk_env.sh
      cd $(build.sourcesdirectory)
      msbuild /r /p:BuildPlatformTarget=Wasm $(build.sourcesdirectory)/src/build/build.csproj
      msbuild /r /p:Configuration=Release $(build.sourcesdirectory)/src/Calculator.Wasm/Calculator.Wasm.csproj

    env:
      GITVERSION_FullSemVer: $(GITVERSION_FullSemVer)
    displayName: 'Build Calculator'

  - task: CopyFiles@2
    displayName: 'Publish Wasm Binaries'
    inputs:
      SourceFolder: $(build.sourcesdirectory)/src/Calculator.Wasm/bin/Release/netstandard2.0/dist
      Contents: '**/*.*'
      TargetFolder: $(build.artifactstagingdirectory)/Uno-Calculator-wasm
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: Uno-Calculator-wasm
      ArtifactType: Container
